package com.uravgcode.chestsortplus.category;

import org.bukkit.Material;

import java.util.List;

public final class RedstoneBlocks implements Category {

    @Override
    public List<Material> materials() {
        return List.of(
            Material.REDSTONE,
            Material.REDSTONE_TORCH,
            Material.REDSTONE_BLOCK,
            Material.REPEATER,
            Material.COMPARATOR,
            Material.TARGET,
            Material.WAXED_COPPER_BULB,
            Material.WAXED_EXPOSED_COPPER_BULB,
            Material.WAXED_WEATHERED_COPPER_BULB,
            Material.WAXED_OXIDIZED_COPPER_BULB,
            Material.LEVER,
            Material.OAK_BUTTON,
            Material.STONE_BUTTON,
            Material.OAK_PRESSURE_PLATE,
            Material.STONE_PRESSURE_PLATE,
            Material.LIGHT_WEIGHTED_PRESSURE_PLATE,
            Material.HEAVY_WEIGHTED_PRESSURE_PLATE,
            Material.SCULK_SENSOR,
            Material.CALIBRATED_SCULK_SENSOR,
            Material.SCULK_SHRIEKER,
            Material.AMETHYST_BLOCK,
            Material.WHITE_WOOL,
            Material.TRIPWIRE_HOOK,
            Material.STRING,
            Material.LECTERN,
            Material.DAYLIGHT_DETECTOR,
            Material.WAXED_LIGHTNING_ROD,
            Material.PISTON,
            Material.STICKY_PISTON,
            Material.SLIME_BLOCK,
            Material.HONEY_BLOCK,
            Material.DISPENSER,
            Material.DROPPER,
            Material.CRAFTER,
            Material.HOPPER,
            Material.CHEST,
            Material.WAXED_COPPER_CHEST,
            Material.BARREL,
            Material.CHISELED_BOOKSHELF,
            Material.OAK_SHELF,
            Material.FURNACE,
            Material.TRAPPED_CHEST,
            Material.JUKEBOX,
            Material.DECORATED_POT,
            Material.OBSERVER,
            Material.NOTE_BLOCK,
            Material.COMPOSTER,
            Material.CAULDRON,
            Material.RAIL,
            Material.POWERED_RAIL,
            Material.DETECTOR_RAIL,
            Material.ACTIVATOR_RAIL,
            Material.MINECART,
            Material.HOPPER_MINECART,
            Material.CHEST_MINECART,
            Material.FURNACE_MINECART,
            Material.TNT_MINECART,
            Material.OAK_CHEST_BOAT,
            Material.BAMBOO_CHEST_RAFT,
            Material.OAK_DOOR,
            Material.IRON_DOOR,
            Material.OAK_FENCE_GATE,
            Material.OAK_TRAPDOOR,
            Material.IRON_TRAPDOOR,
            Material.TNT,
            Material.REDSTONE_LAMP,
            Material.BELL,
            Material.BIG_DRIPLEAF,
            Material.ARMOR_STAND,
            Material.REDSTONE_ORE
        );
    }
}
